### ISSUE TITLE
SDK does not have support for binaryblob

### ISSUE THREAD

**Issue by nesvera** [astarte-platform/astarte-device-sdk-qt5#11]
The current version of the SDK does not have support for a endpoint with type binaryblob. The following log is presented when a interface with this type is loaded.

```
[04/11/2020 22:06:45] {Warning} 	 "Type binaryblob unspecified!"
```

There is a type binary mentioned inside "AstarteDeviceSDK::typeStringToVariantType" but it is not possible to use it because Astarte does not support this type of endpoint.

@rbino mentioned that this is a bug in the implementation.

**Comment by rbino** [comment]
Closing this since it was fixed with https://github.com/astarte-platform/astarte-device-sdk-qt5/pull/13
