### ISSUE TITLE
SDK does not have support for binaryblobarray

### ISSUE THREAD

**Issue by nesvera** [astarte-platform/astarte-device-sdk-qt5#12]
The current version of the SDK does not have support for a endpoint with type binaryblobarray. The following log is presented when a interface with this type is loaded.

```
[04/11/2020 22:06:45] {Warning} 	 "Type binaryblobarray unspecified!"
```

@rbino mentioned that this issue is a missing feature.

**Comment by bettio** [comment]
This issue has been fixed with: https://github.com/astarte-platform/astarte-device-sdk-qt5/pull/33
The fix will be released with Astarte >= 1.0.1.
